// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PGSTask.Web_Jakub_Rzepka.DAL;

namespace PGSTask.Web_Jakub_Rzepka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190717140009_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PGSTask.Web_Jakub_Rzepka.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new { Id = 1, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 877, DateTimeKind.Local), Description = "Test task 3463" },
                        new { Id = 2, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 880, DateTimeKind.Local), Description = "Test task 3456" },
                        new { Id = 3, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 880, DateTimeKind.Local), Description = "Test task 2345" },
                        new { Id = 4, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 880, DateTimeKind.Local), Description = "Test task 3465" },
                        new { Id = 5, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 880, DateTimeKind.Local), Description = "Test task 4566" },
                        new { Id = 6, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 880, DateTimeKind.Local), Description = "Test task 3456" },
                        new { Id = 7, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 880, DateTimeKind.Local), Description = "Test task 2456" },
                        new { Id = 8, CreatedAt = new DateTime(2019, 7, 17, 16, 0, 8, 880, DateTimeKind.Local), Description = "Test task 1356" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
