// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PGSTask.Web_Jakub_Rzepka.DAL;

namespace PGSTask.Web_Jakub_Rzepka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PGSTask.Web_Jakub_Rzepka.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<bool>("IsDone");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new { Id = 1, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 527, DateTimeKind.Local), Description = "Test task 3463", IsDone = false },
                        new { Id = 2, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 530, DateTimeKind.Local), Description = "Test task 3456", IsDone = false },
                        new { Id = 3, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 530, DateTimeKind.Local), Description = "Test task 2345", IsDone = false },
                        new { Id = 4, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 530, DateTimeKind.Local), Description = "Test task 3465", IsDone = false },
                        new { Id = 5, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 530, DateTimeKind.Local), Description = "Test task 4566", IsDone = false },
                        new { Id = 6, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 530, DateTimeKind.Local), Description = "Test task 3456", IsDone = false },
                        new { Id = 7, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 530, DateTimeKind.Local), Description = "Test task 2456", IsDone = false },
                        new { Id = 8, CreatedAt = new DateTime(2019, 7, 17, 14, 52, 34, 530, DateTimeKind.Local), Description = "Test task 1356", IsDone = false }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
